frr defaults traditional
hostname r2
!
interface eth1
 ip address 10.0.12.2/30
interface eth2
 ip address 10.0.23.1/30
!
router bgp 65002
 bgp router-id 2.2.2.2
 no bgp ebgp-requires-policy
 neighbor 10.0.12.1 remote-as 65001
 neighbor 10.0.23.2 remote-as 65003
!
